<img src="../../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# pandas walkthrough for Exploratory Data Analysis - Solution
---

In [1]:
import pandas as pd

# read the dataset as a DataFrame into a variable named 'prod_df'
prod_df = pd.read_csv('../data/Production.Product.csv', sep='\t')

## Independent Exercises

Do your best to complete the following prompts. Don't hesitate to look at code we wrote together!

Print the first 4 rows of the whole DataFrame.

In [2]:
prod_df.head(4)

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,0,0,NaN,1000,750,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{694215B7-08F7-4C0D-ACB1-D734BA44C0C8},2014-02-08 10:01:36.827000000
1,2,Bearing Ball,BA-8327,0,0,NaN,1000,750,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{58AE3C20-4F3A-4749-A7D4-D568806CC537},2014-02-08 10:01:36.827000000
2,3,BB Ball Bearing,BE-2349,1,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{9C21AED2-5BFA-4F18-BCB8-F11638DC2E4E},2014-02-08 10:01:36.827000000
3,4,Headset Ball Bearings,BE-2908,0,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{ECFED6CB-51FF-49B5-B06C-7D8AC834DB8B},2014-02-08 10:01:36.827000000

How many rows are in the dataframe? Return the answer as an int.

In [3]:
prod_df.shape[0]

504

How many columns? Return the answer as an int.

In [4]:
prod_df.shape[1]

25

How many different product lines are there?

In [5]:
prod_df['ProductLine'].nunique()

4

What are the values of these product lines?

In [6]:
list(prod_df['ProductLine'].unique())

[nan, 'R ', 'S ', 'M ', 'T ']

Do the number of values for the product lines match the number you have using `.nunique()`? Why or why not?

In [7]:
# .nunique ignores NaN by default.

Take the output from your previous answer (using `.unique()`). Select the label corresponding to the `Road` product line using list indexing notation. How many characters are in this string?

In [8]:
print(prod_df['ProductLine'].unique()[1])
len(prod_df['ProductLine'].unique()[1])

R

2

Do you notice anything odd about this?

In [9]:
# there's a trailing whitespace

How many products are there for the `Road` product line? Don't forget what you just worked on above! Return your answer as an int.

In [10]:
is_road = prod_df['ProductLine'] == 'R '

prod_df[is_road].shape[0]

100

How many products are there in the `Women's` `Mountain` category? Return your answer as an int. _Hint: Use the data dictionary above!_

In [11]:
is_women_mountain = (prod_df['ProductLine'] == 'M ') & (prod_df['Style'] == 'W ')
prod_df[is_women_mountain].shape[0]

11

In [12]:
prod_df[is_women_mountain]

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
371,867,"Women's Mountain Shorts, S",SH-W890-S,0,1,Black,4,3,26.1763,69.99,...,M,NaN,W,22.0,37.0,2013-05-30 00:00:00,NaN,NaN,{22616FD2-B99F-4F7D-ACF6-33DFF66D42D2},2014-02-08 10:01:36.827000000
372,868,"Women's Mountain Shorts, M",SH-W890-M,0,1,Black,4,3,26.1763,69.99,...,M,NaN,W,22.0,37.0,2013-05-30 00:00:00,NaN,NaN,{968E3610-E583-42E8-8AB6-484A799B1774},2014-02-08 10:01:36.827000000
373,869,"Women's Mountain Shorts, L",SH-W890-L,0,1,Black,4,3,26.1763,69.99,...,M,NaN,W,22.0,37.0,2013-05-30 00:00:00,NaN,NaN,{1A66B244-5CA0-4153-B539-AE048D14FAEC},2014-02-08 10:01:36.827000000
408,904,"ML Mountain Frame-W - Silver, 40",FR-M63S-40,1,1,Silver,500,375,199.3757,364.09,...,M,M,W,12.0,15.0,2013-05-30 00:00:00,NaN,NaN,{A7DDE43E-F7D5-4075-A0C1-C866AD7AA154},2014-02-08 10:01:36.827000000
409,905,"ML Mountain Frame-W - Silver, 42",FR-M63S-42,1,1,Silver,500,375,199.3757,364.09,...,M,M,W,12.0,15.0,2013-05-30 00:00:00,NaN,NaN,{D4A2FCAD-1E63-4EBD-863C-5A7C48D5B8D9},2014-02-08 10:01:36.827000000
410,906,"ML Mountain Frame-W - Silver, 46",FR-M63S-46,1,1,Silver,500,375,199.3757,364.09,...,M,M,W,12.0,15.0,2013-05-30 00:00:00,NaN,NaN,{82025C63-7B28-412D-92C1-408E0E6AE646},2014-02-08 10:01:36.827000000
446,942,"ML Mountain Frame-W - Silver, 38",FR-M63S-38,1,1,Silver,500,375,199.3757,364.09,...,M,M,W,12.0,15.0,2013-05-30 00:00:00,NaN,NaN,{BA3646B0-1487-426E-AB4E-57D42E6F9233},2014-02-08 10:01:36.827000000
484,980,"Mountain-400-W Silver, 38",BK-M38S-38,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{7A927632-99A4-4F24-ADCE-0062D2D113D9},2014-02-08 10:01:36.827000000
485,981,"Mountain-400-W Silver, 40",BK-M38S-40,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{0A72791C-A984-4733-AE4E-2B4373CFD7CD},2014-02-08 10:01:36.827000000
486,982,"Mountain-400-W Silver, 42",BK-M38S-42,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{4EA4FE06-AAEA-42D4-A9D9-69F6A9A4A042},2014-02-08 10:01:36.827000000
487,983,"Mountain-400-W Silver, 46",BK-M38S-46,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{0B0C8EE4-FF2D-438E-9CAC-464783B86191},2014-02-08 10:01:36.827000000

**Challenge:** What are the top 3 _most expensive list price_ product that are either in the `Women's` `Mountain` category, _OR_ `Silver` in `Color`? Return your answer as a DataFrame object, with the `ProductID` index, `Name` relabeled as `NewName`, and `ListPrice` columns. Perform the statement in one execution, and do not mutate the source DataFrame.

In [13]:
# create boolean indices
is_women_mountain = (prod_df['ProductLine'] == 'M ') & (prod_df['Style'] == 'W ')
is_silver = prod_df['Color'] == 'Silver'

is_wm_silver = is_women_mountain | is_silver

# create placeholders for column name lists and dictionaries
cols = ['Name', 'ListPrice']
new_cols = {'Name': 'NewName'}

prod_df[is_wm_silver].sort_values(by='ListPrice', ascending=False).head(3)[cols].rename(columns=new_cols)

                     NewName  ListPrice
278  Mountain-100 Silver, 48    3399.99
275  Mountain-100 Silver, 38    3399.99
276  Mountain-100 Silver, 42    3399.99

**End**